sample/urls.py
# Use include() to add paths from the blood application
from django.urls import path
from django.urls import re_path
from . import views
from django.views import generic
from django.conf.urls import url
from django.views.generic.list import ListView

urlpatterns = [
    path('', views.index, name='index'),
    #all the freezer urls
    re_path(r'^freezer/$',views.FreezerListView.as_view(), name='freezer'),
    re_path(r'^freezer/(?P<pk>\d+)/$',views.FreezerDetailView.as_view(), name='freezer-detail'),
    re_path(r'^freezer/create/$',views.FreezerCreate.as_view(),name='freezer-create'),
    re_path(r'^freezer/(?P<pk>\d+)/update/$',views.FreezerUpdate.as_view(),name='freezer-update'),
    re_path(r'^freezer/(?P<pk>\d+)/delete/$',views.FreezerDelete.as_view(),name='freezer-delete'),
    #all the compartments urls
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<pk>\d+)/$',views.CompartmentDetailView.as_view(), name='compartment-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/create/$',views.CompartmentCreate.as_view(),name='compartment-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<pk>\d+)/update/$',views.CompartmentUpdate.as_view(),name='compartment-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<pk>\d+)/delete/$',views.CompartmentDelete.as_view(),name='compartment-delete'),
    #all the rack urls
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<pk>\d+)/$',views.RackDetailView.as_view(), name='rack-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/create/$',views.RackCreate.as_view(),name='rack-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<pk>\d+)/update/$',views.RackUpdate.as_view(),name='rack-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<pk>\d+)/delete/$',views.RackDelete.as_view(),name='rack-delete'),
    #all the rackmodule urls
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<pk>\d+)/$',views.RackmoduleDetailView.as_view(), name='rackmodule-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/create/$',views.RackmoduleCreate.as_view(),name='rackmodule-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<pk>\d+)/update/$',views.RackmoduleUpdate.as_view(),name='rackmodule-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<pk>\d+)/delete/$',views.RackmoduleDelete.as_view(),name='rackmodule-delete'),
    #all the box urls
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<pk>\d+)/$',views.BoxRackDetailView.as_view(), name='box-r-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/create/$',views.BoxRackCreate.as_view(),name='box-r-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<pk>\d+)/update/$',views.BoxRackUpdate.as_view(),name='box-r-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<pk>\d+)/delete/$',views.BoxRackDelete.as_view(),name='box-r-delete'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<pk>\d+)/$',views.BoxCompartmentDetailView.as_view(), name='box-c-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/create/$',views.BoxCompartmentCreate.as_view(),name='box-c-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<pk>\d+)/update/$',views.BoxCompartmentUpdate.as_view(),name='box-c-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<pk>\d+)/delete/$',views.BoxCompartmentDelete.as_view(),name='box-c-delete'),
    #all the tube urls
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/$',views.TubeRackDetailView.as_view(),name='tube-r-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<box>\d+)/tube/create/$',views.TubeRackCreate.as_view(),name='tube-r-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/update/$',views.TubeRackUpdate.as_view(),name='tube-r-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/delete/$',views.TubeRackDelete.as_view(),name='tube-r-delete'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/$',views.TubeCompartmentDetailView.as_view(), name='tube-c-detail'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<box>\d+)/tube/create/$',views.TubeCompartmentCreate.as_view(),name='tube-c-create'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/update/$',views.TubeCompartmentUpdate.as_view(),name='tube-c-update'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/box/(?P<box>\d+)/tube/(?P<pk>\d+)/delete/$',views.TubeCompartmentDelete.as_view(),name='tube-c-delete'),
    re_path(r'^biosample/(?P<biosample>\d+)/tube/create/$',views.TubeBiosampleCreate.as_view(),name='tube-b-create'),
    #all the biosample urls
    re_path(r'^biosample/$',views.BioSampleListView.as_view(), name='biosample'),
    re_path(r'^biosample/(?P<pk>\d+)/$',views.BioSampleDetailView.as_view(), name='biosample-detail'),
    re_path(r'^biosample/create/$',views.BioSampleCreate.as_view(),name='biosample-create'),
    re_path(r'^biosample/(?P<pk>\d+)/update/$',views.BioSampleUpdate.as_view(),name='biosample-update'),
    re_path(r'^biosample/(?P<pk>\d+)/delete/$',views.BioSampleDelete.as_view(),name='biosample-delete'),
    #all the type urls
    re_path(r'^type/$',views.TypeListView.as_view(), name='type'),
    re_path(r'^type/(?P<pk>\d+)/$',views.TypeDetailView.as_view(), name='type-detail'),
    re_path(r'^type/create/$',views.TypeCreate.as_view(),name='type-create'),
    re_path(r'^type/(?P<pk>\d+)/update/$',views.TypeUpdate.as_view(),name='type-update'),
    re_path(r'^type/(?P<pk>\d+)/delete/$',views.TypeDelete.as_view(),name='type-delete'),
    re_path(r'^biosample/type/(?P<pk>\d+)/update/$',views.TypeUpdateModal.as_view(),name='type-update-modal'),
    re_path(r'^biosample/type/create/$',views.TypeCreateModal.as_view(),name='type-create-modal'),
    # AJAX
    path('ajax/load-compartments/', views.load_compartments, name='ajax_load_compartments'),
    path('ajax/load-racks/', views.load_racks, name='ajax_load_racks'),
    path('ajax/load-rackmodules/', views.load_rackmodules, name='ajax_load_rackmodules'),
    # Upload
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/rack/(?P<rack>\d+)/rackmodule/(?P<rackmodule>\d+)/uploads/$', views.model_form_upload_rack, name='upload-rack'),
    re_path(r'^freezer/(?P<freezer>\d+)/compartment/(?P<compartment>\d+)/uploads/$', views.model_form_upload_compartment, name='upload-compartment'),
    #url(r'^upload/$', views.model_form_upload, name='upload'),
    # re_path(r'^search/$', views.FreezerSearchListView.as_view(), name="freezer_search_list_view"),
    re_path(r'^search/$', views.SearchListView.as_view(), name="search_list_view"),

]

samplefreez/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/', include('sample.urls')),
    path('',RedirectView.as_view(url='/sample/',permanent=True)),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
# accounts.models.py

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class UserManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, password):
        """
        Creates and saves a User with the given username and password.
        """
        if not email:
            raise ValueError('Users must have an email')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, username, first_name, last_name, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            username=username,
            password=password,
        )

        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, first_name, last_name, password):
        """
        Creates and saves a superuser with the given username and password.
        """
        user = self.create_user(
            email,
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)

        return user

class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    THEME_CHOICES = (
        ('cerulean','Cerulean'),
        ('cosmo','Cosmo'),
        ('cyborg','Cyborg'),
        ('darkly','Darkly'),
        ('flatly','Flatly'),
        ('journal','Journal'),
        ('lietra','Lietra'),
        ('lumen','Lumen'),
        ('lux','Lux'),
        ('materia','Matria'),
        ('minty','Minty'),
        ('pulse','Pulse'),
        ('sandstone','Sandstone'),
        ('simplex','Simplex'),
        ('sketchy','Sketchy'),
        ('slate','Slate'),
        ('solar','Solar'),
        ('spacelab','Spacelab'),
        ('superhero','Superhero'),
        ('united','United'),
        ('yeti','Yeti'),
    )

    theme = models.CharField(max_length=50, choices=THEME_CHOICES,  blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=20, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False) # a admin user; non super-user
    admin = models.BooleanField(default=False) # a superuser
    # notice the absence of a "Password field", that's built in.

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','first_name','last_name',] # Username & Password are required by default.

    def get_full_name(self):
        # The user is identified by their email address
        return self.first_name + ' ' + self.last_name

    def get_short_name(self):
        # The user is identified by their email address
        return self.first_name

    def __str__(self):              # __unicode__ on Python 2
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # All admins have permissions
        return self.is_admin

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active

    objects = UserManager()

sample/templates/sample/all_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if freezer_list %}
    <table class="table table-hover">
      <thead>
        <tr class="table-secondary">
          <th><h3>Freezers</h3></th>
        </tr>
      </thead>
      <tbody>
          {% for freezer in freezer_list %}
            <tr class="table-secondary">
              <td><a href="{{ freezer.get_absolute_url }}">{{ freezer.name }}</a></td>
            </tr>
          {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if compartment_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Compartments</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for compartment in compartment_list %}
          <tr class="table-secondary">
            <td><a href={% url 'compartment-detail' compartment.freezer.id compartment.id %}>{{ compartment.freezer.name }} / {{ compartment.name }}</a></td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if rack_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Racks</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for rack in rack_list %}
          <tr class="table-secondary">
            <td>
              <a href={% url 'rack-detail' rack.compartment.freezer.id rack.compartment.id rack.id %}>
              {{ rack.compartment.freezer.name }} /
              {{ rack.compartment.name }} /
              {{ rack.name }}
              </a>
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if rackmodule_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Rackmodules</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for rackmodule in rackmodule_list %}
          <tr class="table-secondary">
            <td>
              <a href={% url 'rackmodule-detail' rackmodule.rack.compartment.freezer.id rackmodule.rack.compartment.id rackmodule.rack.id rackmodule.id %}>
              {{ rackmodule.rack.compartment.freezer.name }} /
              {{ rackmodule.rack.compartment.name }} /
              {{ rackmoduel.rack.name }} /
              {{ rackmodule.name }}
              </a>
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if box_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Boxes</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for box in box_list %}
          <tr class="table-secondary">
            {% if box.rack %}
            <td>
              <a href={% url 'box-r-detail' box.freezer.id box.compartment.id box.rack.id box.rackmodule.id box.id %}>
              {{ box.freezer.name }} /
              {{ box.compartment.name }} /
              {{ box.rack.name }} /
              {{ box.rackmodule.name }} /
              {{ box.name }}
              </a>
            </td>
            {% else %}
            <td>
              <a href={% url 'box-c-detail' box.freezer.id box.compartment.id box.id %}>
              {{ box.freezer.name }} /
              {{ box.compartment.name }} /
              {{ box.name }}
              </a>
            </td>
            {% endif %}
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if tube_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Tubes</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for tube in tube_list %}
        <tr class="table-secondary">
          {% if tube.box.rack %}
          <td>
            <a href={% url 'tube-r-detail' tube.box.freezer.id tube.box.compartment.id tube.box.rack.id tube.box.rackmodule.id tube.box.id tube.id %}>
            {{ tube.box.freezer.name }} /
            {{ tube.box.compartment.name }} /
            {{ tube.box.rack.name }} /
            {{ tube.box.rackmodule.name }} /
            {{ tube.box.name }}
            </a>
          </td>
          {% else %}
          <td>
            <a href={% url 'tube-c-detail' tube.box.freezer.id tube.box.compartment.id tube.box.id tube.id %}>
            {{ tube.box.freezer.name }} /
            {{ tube.box.compartment.name }} /
            {{ tube.box.name }} /
            {{ tube.name }}
            </a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if biosample_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Biosamples</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for biosample in biosample_list %}
          <tr class="table-secondary">
            <td><a href={% url 'biosample-detail' biosample.id %}>{{ biosample.name }}</a></td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if type_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th><h3>Types</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for type in type_list %}
          <tr class="table-secondary">
            <td><a href={% url 'type-detail' type.id %}> {{ type.name }}</a></td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if user_list %}
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th colspan="3"><h3>User</h3></th>
      </tr>
    </thead>
    <tbody>
        {% for user in user_list %}
          <tr class="table-secondary">
            <td>{{ user.username }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.first_name }}</td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
{% endif %}

{% if not freezer_list and  not compartment_list and not rack_list and not rackmodule_list and not box_list and not tube_list and not biosample_list and not type_list  and not user_list%}
 <h3>Nothing found</h3>
{% endif %}

{% endblock %}

sample/templates/sample/model_form_upload.html
{% extends 'base_generic.html' %}

{% block content %}
    {% load widget_tweaks %}

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
      {% endfor %}

      {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
          {% for error in form.non_field_errors %}
            {{ error }}
          {% endfor %}
        </div>
      {% endif %}

      <table class="table table-hover">
      <tbody>
      {% for field in form.visible_fields %}
          <tr class="table-secondary">
          <th>{{ field.label_tag }}</th>
          <td>
          {% if form.is_bound %}
            {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                  <div class="invalid-feedback">
                    {{ error }}
                  </div>
                {% endfor %}
            {% else %}
                {% render_field field class="form-control is-valid" %}
            {% endif %}
          {% else %}
              {% render_field field class="form-control" %}
          {% endif %}

          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
    </table>
    <button type="submit" class="btn btn-outline-success">Upload</button>
  </form>
{% endblock %}